apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: mule
spec:
  containers:
  - name: maven
    image: maven:3.6-slim
    securityContext:
      privileged: true
    tty: true 
    command: cat

