---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${appName}
  namespace: ${projectName}-${appEnv}
  labels:
    app: ${appName}
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.${appName}: regex:^${appEnv}-.*
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ${appName}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ${appName}
    spec:
      containers:
      - name: ${appName}
        image: ${dockerRegistryUrl}/${projectName}/${appName}:${appEnv}-latest
        imagePullPolicy: Always
        ports:
        - containerPort: ${appPort}
          name: http
          protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: ${appName}
  namespace: ${projectName}-${appEnv}
spec:
  ports:
  - name: ${appName}
    port: ${appPort}
    protocol: TCP
    targetPort: ${appPort}
  selector:
    app: ${appName}
  type: ClusterIP
