---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${repoName}
  namespace: ${projectName}-${appEnv}
  labels:
    app: ${repoName}
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.${repoName}: regex:^${appEnv}-.*
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ${repoName}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ${repoName}
    spec:
      containers:
      - name: ${repoName}
        image: ${dockerRegistryUrl}/${projectName}/${repoName}:${appEnv}-latest
        imagePullPolicy: Always
        ports:
        - containerPort: ${appPort}
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: ${repoName}
  namespace: ${projectName}-${appEnv}
spec:
  ports:
  - name: ${repoName}
    port: ${appPort}
    protocol: TCP
    targetPort: ${appPort}
  selector:
    app: ${repoName}
  type: ClusterIP
