apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${appName}-${appEnv}-vs
  namespace: istio-system
spec:
  hosts:
  - "${appName}-${appEnv}.kube.cloudappNames.ms3-inc.com"
  gateways:
  - ${appName}-${appEnv}-gateway
  http:
  - route:
    - destination:
        host: ${appName}-service.java-springboot-apps.svc.cluster.local
        port:
          number: ${appPort}