# This snippet should be added to the Istio Gateway configuration
  - hosts:
    - "${repoName}-${appEnv}.kube.cloudapps.ms3-inc.com"
    port:
      number: 80
      name: ${repoName}-${appEnv}-http
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - "${repoName}-${appEnv}.kube.cloudapps.ms3-inc.com"
    port:
      number: 443
      name: ${repoName}-${appEnv}-https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: cloudapps-wildcard