def artifactName
def version
pipeline {
  agent {
    kubernetes {
      label 'node'
      yamlFile 'angular/kubernetes.yaml'
    }
  }
  stages {
    stage ('Checkout SCM') {
      steps{
        container('jnlp'){
          script{
            echo "Checking out from branch "+"${branch}"
            timeout(time: Integer.parseInt("$gitclone_timeout"), unit: 'SECONDS') {
              retry(3) {
                checkout([$class: 'GitSCM', branches: [[name: '*/'+"$branch"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'bitbucket to jenkins', url: "$application_git_url"]]])
              }
            }
          }
        }
      }
    }
    stage('Build') {
      steps{
        container('node'){
         sh '''#!/bin/bash
           npm install -g @angular/cli@7.0.6;
           pwd;
           ls -all;
           ng build;
           ls -all;
         '''
        }
      }
    }
  }
}
