apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: mule
  namespace: jenkins
spec:
  containers:
  - name: maven
    image: maven:3.6.1-alpine
    tty: true 
    command: ['cat']
  - name: anypoint-cli
    image: docker.kube.cloudapps.ms3-inc.com/anypoint-cli/3:1
    tty: true 
    command: ['cat']
  - name: newman
    image: yourdevops/newman-html-reporter:5.1-alpine
    tty: true 
    command: ['cat']
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 256Mi
  imagePullSecrets:
    - name: nexus
