apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-dind
  namespace: jenkins
spec: 
  containers:
  - name: maven
    image: maven:3.6-alpine
    securityContext:
      privileged: true
    tty: true 
    command: ['cat']
  - name: maven-jdk-14
    image: maven:3.6-openjdk-14-slim
    securityContext:
      privileged: true
    tty: true 
    command: ['cat']
  - name: dind
    image: docker:18.05-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  - name: kubectl
    image: docker-public.kube.cloudapps.ms3-inc.com/kubectl/1.14.3
    securityContext:
      privileged: true
    tty: true
    command: ['cat']
  - name: git-in-docker
    image: docker-public.kube.cloudapps.ms3-inc.com/cicd-tools/git-in-docker:dev-8fbe659
    tty: true
    command: ['cat']
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 256Mi
  volumes:
    - name: dind-storage
      emptyDir: {}
  imagePullSecrets:
    - name: nexus
