apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-dind
  namespace: jenkins
spec: 
  containers:
  - name: maven
    image: maven:3.6-slim
    securityContext:
      privileged: true
    tty: true 
    command: ['cat']
  - name: dind
    image: docker:18.05-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
  imagePullSecrets:
    - name: nexus
