apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: maven
  namespace: jenkins
spec:
  containers:
  - name: maven
    image: maven:3.6-alpine
    securityContext:
      privileged: true
    tty: true 
    command: ['cat']
