apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: sow-dind
spec: 
  containers:
  - name: dind
    image: docker:18.05-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  - name: kubectl
    image: docker.kube.cloudapps.ms3-inc.com/kubectl/1.14.3
    ecurityContext:
      privileged: true
    tty: true
    command: ['cat']
  - name: node
    image: node:11-alpine
    ecurityContext:
      privileged: true
    tty: true
    command: ['cat']
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 256Mi
  volumes:
    - name: dind-storage
      emptyDir: {}
  imagePullSecrets:
    - name: nexus
