# Just a Docker-in-Docker agent manifest
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: sow-dind
spec: 
  containers:
  - name: dind
    image: docker:19.03-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 256Mi
  volumes:
    - name: dind-storage
      emptyDir: {}
  imagePullSecrets:
    - name: nexus
